---
- hosts: web-servers
  user: vagrant
  sudo: True

  vars:
     bind_address: "127.0.0.1" 
     key_buffer: "16M"
     
  tasks:
     - include: mysql/tasks/setup.yml

  handlers:
     - include: mysql/handlers/handler.yml     
